/*
 * Blocks.cs
 * RVO2 Library C#
 *
 * SPDX-FileCopyrightText: 2008 University of North Carolina at Chapel Hill
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Please send all bug reports to <geom@cs.unc.edu>.
 *
 * The authors may be contacted via:
 *
 * Jur van den Berg, Stephen J. Guy, Jamie Snape, Ming C. Lin, Dinesh Manocha
 * Dept. of Computer Science
 * 201 S. Columbia St.
 * Frederick P. Brooks, Jr. Computer Science Bldg.
 * Chapel Hill, N.C. 27599-3175
 * United States of America
 *
 * <http://gamma.cs.unc.edu/RVO2/>
 */

/*
 * Example file showing a demo with 100 agents split in four groups initially
 * positioned in four corners of the environment. Each agent attempts to move to
 * other side of the environment through a narrow passage generated by four
 * obstacles. There is no roadmap to guide the agents around the obstacles.
 */

#define RVOCS_OUTPUT_TIME_AND_POSITIONS
#define RVOCS_SEED_RANDOM_NUMBER_GENERATOR

using System;
using System.Collections.Generic;
using Unity.Mathematics;
using UnityEngine;
using Random = System.Random;

namespace RVO
{
    public class BlockExample : MonoBehaviour
    {
        /* Store the goals of the agents. */
        public IList<float2> goals;

        /** Random number generator. */
        public Random random;

        private List<int> obstacles = new List<int>(36);

        void Start()
        {
            goals = new List<float2>();
            random = new Random(0);


            setupScenario();
        }

        void setupScenario()
        {
            /* Specify the global time step of the simulation. */
            Simulator.Instance.setTimeStep(0.25f);

            /*
             * Specify the default parameters for agents that are subsequently
             * added.
             */
            Simulator.Instance.setAgentDefaults(15.0f, 10, 5.0f, 5.0f, 2.0f, 2.0f, new float2(0.0f, 0.0f));

            /*
             * Add agents, specifying their start position, and store their
             * goals on the opposite side of the environment.
             */
            for (int i = 0; i < 5; ++i)
            {
                for (int j = 0; j < 5; ++j)
                {
                    Simulator.Instance.addAgent(new float2(55.0f + i * 10.0f, 55.0f + j * 10.0f));
                    goals.Add(new float2(-75.0f, -75.0f));

                    Simulator.Instance.addAgent(new float2(-55.0f - i * 10.0f, 55.0f + j * 10.0f));
                    goals.Add(new float2(75.0f, -75.0f));

                    Simulator.Instance.addAgent(new float2(55.0f + i * 10.0f, -55.0f - j * 10.0f));
                    goals.Add(new float2(-75.0f, 75.0f));

                    Simulator.Instance.addAgent(new float2(-55.0f - i * 10.0f, -55.0f - j * 10.0f));
                    goals.Add(new float2(75.0f, 75.0f));
                }
            }

            /*
             * Add (polygonal) obstacles, specifying their vertices in
             * counterclockwise order.
             */
            IList<float2> obstacle1 = new List<float2>
            {
                new float2(-10.0f, 40.0f),
                new float2(-40.0f, 40.0f),
                new float2(-40.0f, 10.0f),
                new float2(-10.0f, 10.0f)
            };
            obstacles.Add(Simulator.Instance.addObstacle(obstacle1));

            IList<float2> obstacle2 = new List<float2>
            {
                new float2(10.0f, 40.0f),
                new float2(10.0f, 10.0f),
                new float2(40.0f, 10.0f),
                new float2(40.0f, 40.0f)
            };
            obstacles.Add(Simulator.Instance.addObstacle(obstacle2));

            IList<float2> obstacle3 = new List<float2>
            {
                new float2(10.0f, -40.0f),
                new float2(40.0f, -40.0f),
                new float2(40.0f, -10.0f),
                new float2(10.0f, -10.0f)
            };
            obstacles.Add(Simulator.Instance.addObstacle(obstacle3));

            IList<float2> obstacle4 = new List<float2>
            {
                new float2(-10.0f, -40.0f),
                new float2(-10.0f, -10.0f),
                new float2(-40.0f, -10.0f),
                new float2(-40.0f, -40.0f)
            };
            obstacles.Add(Simulator.Instance.addObstacle(obstacle4));

            /*
             * Process the obstacles so that they are accounted for in the
             * simulation.
             */
            Simulator.Instance.processObstacles();
        }

#if RVOCS_OUTPUT_TIME_AND_POSITIONS
        void updateVisualization()
        {
            /* Output the current global time. */
            Console.Write(Simulator.Instance.getGlobalTime());

            /* Output the current position of all the agents. */
            for (int i = 0; i < Simulator.Instance.getNumAgents(); ++i)
            {
                Console.Write(" {0}", Simulator.Instance.getAgentPosition(i));
            }

            Console.WriteLine();
        }
#endif

        void setPreferredVelocities()
        {
            /*
             * Set the preferred velocity to be a vector of unit magnitude
             * (speed) in the direction of the goal.
             */
            for (int i = 0; i < Simulator.Instance.getNumAgents(); ++i)
            {
                float2 goalVector = goals[i] - Simulator.Instance.getAgentPosition(i);

                if (RVOMath.absSq(goalVector) > 1.0f)
                {
                    goalVector = RVOMath.normalize(goalVector);
                }

                Simulator.Instance.setAgentPrefVelocity(i, goalVector);

                /* Perturb a little to avoid deadlocks due to perfect symmetry. */
                float angle = (float)random.NextDouble() * 2.0f * (float)Math.PI;
                float dist = (float)random.NextDouble() * 0.0001f;

                Simulator.Instance.setAgentPrefVelocity(i, Simulator.Instance.getAgentPrefVelocity(i) +
                    dist * new float2((float)Math.Cos(angle), (float)Math.Sin(angle)));
            }
        }

        bool reachedGoal()
        {
            /* Check if all agents have reached their goals. */
            for (int i = 0; i < Simulator.Instance.getNumAgents(); ++i)
            {
                if (RVOMath.absSq(Simulator.Instance.getAgentPosition(i) - goals[i]) > 400.0f)
                {
                    return false;
                }
            }

            return true;
        }


        void Update()
        {
            if (reachedGoal()) return;

#if RVOCS_OUTPUT_TIME_AND_POSITIONS
            // updateVisualization();
#endif
            setPreferredVelocities();
            Simulator.Instance.doStep();
        }

        private void OnDrawGizmos()
        {
            Simulator simulator = Simulator.Instance;

            if (simulator == null)
            {
                return;
            }

            for (int i = obstacles.Count - 1; i >= 0; i--)
            {
                int obstacleId = obstacles[i];
                int current = obstacleId;
                var first = simulator.getObstacleVertex(obstacles[i]);

                while (true)
                {
                    int next = simulator.getNextObstacleVertexNo(current);
                    float2 p0 = simulator.getObstacleVertex(current);
                    float2 p1 = simulator.getObstacleVertex(next);

                    Gizmos.DrawLine((Vector2)p0, (Vector2)p1);

                    if (next == obstacleId)
                    {
                        break;
                    }

                    current = next;
                }
            }

            for (int i = 0; i < simulator.getNumAgents(); ++i)
            {
                Gizmos.DrawSphere((Vector2)simulator.getAgentPosition(i), 2);
            }
        }
    }
}
